server:
  port: 18081
  servlet:
    context-path: /api
spring:
  profiles:
    group:
      local: local, common
      dev: dev, common
      prod: prod, common
logging:
  config: classpath:logback/logback-${spring.profiles.active}.xml
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hanjin_sm
    username: psqluser
    password: psqluser
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create" after "update"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hanjin_sm
    username: psqluser
    password: psqluser
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hanjin_sm
    username: psqluser
    password: psqluser
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
---
spring:
  config:
    activate:
      on-profile: common
---